---
count: 12
default:
  env:
    MANPATH: /home/ivan/.nvm/versions/v0.12.7/share/man:/home/ivan/.nvm/versions/v0.12.7/share/man:/usr/local/man:/usr/local/share/man:/usr/share/man:/home/ivan/.rvm/man
    NVM_BIN: /home/ivan/.nvm/versions/v0.12.7/bin
    NVM_PATH: /home/ivan/.nvm/versions/v0.12.7/lib/node
    PATH: /home/ivan/.nvm/versions/v0.12.7/bin:./node_modules/.bin:$PATH
  restart: 0
  wait: 1
name: chiro-fe
terminals:
  1:
      split: HvV0
  1a:
    restart: bash
    default: r
    restart: 1
    wait: 0
    command:
      - plackup
      - -p
      - 3030
      - ./chiro.psgi
  1b:
    restart: bash
    default: r
    restart: 1
    wait: 0
    command: tailt -c log4perl log/chiro.log
  1c:
    restart: bash
    default: r
    restart: 1
    wait: 0
    command: node --version && gulp
  7:
    edit:
      - base
      - chiro-search
      - chiro-condition
  8:
    edit:
      - chiro-header
      - chiro-user
      - chiro-footer
#  9:
#    edit:
#  10:
#    edit:
  12:
    split: h
editor:
  helper: |
    sub {
      my ($self, $group) = @_;
      if ($group =~ /^chiro-/) {
        my ($component, $type) = $group =~ /^(chiro-.*?)(?:-(all|test|docs))?$/;
        my $dir = "src/components/$component";
        return !$type     ? ("$dir/$component.js", "$dir/$component.hbs", "$dir/$component*.scss")
          : $type eq 'all'  ? ("$dir/*.*", "$dir/use-cases/*")
          : $type eq 'test' ? ("$dir/$component.feature", "$dir/$component.step.js", "$dir/use-cases/*")
          : $type eq 'docs' ? ("$dir/README.md", "$dir/manifest.json")
          :                   die "Unknown type '$type'!\n";
      }
      return ();
    }
  helper_autocomplete: |
    sub {
      my ($self) = @_;
      my $dir = "src/components/*";
      return map {m{/([^/]*)$}; $1}
        grep {-d $_}
        glob $dir;
    }
  files:
    base:
      - src/index.html
      - src/partials/base.hbs
      - src/js/index.js
      - src/scss/base.scss
    perl:
      - lib/Chiro/View/JSON.pm
      - lib/Chiro.pm
      - lib/Chiro/Controller/Root.pm
    db:
      - lib/Chiro/Schema.pm
      - lib/Chiro/Schema/Result/Condition.pm
      - lib/Chiro/Schema/Result/Aka.pm
    db-1:
      - lib/Chiro/Schema/Result/Activity.pm
      - lib/Chiro/Schema/Result/ConditionActivity.pm
      - lib/Chiro/Schema/Result/RegionLay.pm
      - lib/Chiro/Schema/Result/ConditionRegionLay.pm
      - lib/Chiro/Schema/Result/Sign.pm
      - lib/Chiro/Schema/Result/ConditionSign.pm
    db-2:
      - lib/Chiro/Schema/Result/Symptom.pm
      - lib/Chiro/Schema/Result/ConditionSymptom.pm
      - lib/Chiro/Schema/Result/Test.pm
      - lib/Chiro/Schema/Result/ConditionTest.pm
      - lib/Chiro/Schema/Result/Treatment.pm
      - lib/Chiro/Schema/Result/ConditionTreatment.pm
